# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0005_auto_20171002_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='result_proof',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
