# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:31
from __future__ import unicode_literals

from django.db import migrations
import helios.datatypes
import helios.datatypes.djangofield


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0006_auto_20171003_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castvote',
            name='vote',
            field=helios.datatypes.djangofield.LDObjectField(type_hint='legacy/EncryptedVote'),
        ),
        migrations.AlterField(
            model_name='election',
            name='eligibility',
            field=helios.datatypes.djangofield.LDObjectField(null=True, type_hint='legacy/Eligibility'),
        ),
        migrations.AlterField(
            model_name='election',
            name='encrypted_tally',
            field=helios.datatypes.djangofield.LDObjectField(null=True, type_hint='legacy/Tally'),
        ),
        migrations.AlterField(
            model_name='election',
            name='private_key',
            field=helios.datatypes.djangofield.LDObjectField(null=True, type_hint='legacy/EGSecretKey'),
        ),
        migrations.AlterField(
            model_name='election',
            name='public_key',
            field=helios.datatypes.djangofield.LDObjectField(null=True, type_hint='legacy/EGPublicKey'),
        ),
        migrations.AlterField(
            model_name='election',
            name='questions',
            field=helios.datatypes.djangofield.LDObjectField(null=True, type_hint='legacy/Questions'),
        ),
        migrations.AlterField(
            model_name='election',
            name='result',
            field=helios.datatypes.djangofield.LDObjectField(null=True, type_hint='legacy/Result'),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='decryption_factors',
            field=helios.datatypes.djangofield.LDObjectField(null=True, type_hint=helios.datatypes.arrayOf(helios.datatypes.arrayOf('core/BigInteger'))),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='decryption_proofs',
            field=helios.datatypes.djangofield.LDObjectField(null=True, type_hint=helios.datatypes.arrayOf(helios.datatypes.arrayOf('legacy/EGZKProof'))),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='pok',
            field=helios.datatypes.djangofield.LDObjectField(null=True, type_hint='legacy/DLogProof'),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='public_key',
            field=helios.datatypes.djangofield.LDObjectField(null=True, type_hint='legacy/EGPublicKey'),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='secret_key',
            field=helios.datatypes.djangofield.LDObjectField(null=True, type_hint='legacy/EGSecretKey'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote',
            field=helios.datatypes.djangofield.LDObjectField(null=True, type_hint='legacy/EncryptedVote'),
        ),
    ]
